const GET_ORDER_DETAILS_REQUEST = "GET_ORDER_DETAILS_REQUEST";
const GET_ORDER_DETAILS_SUCCESS = "GET_ORDER_DETAILS_SUCCESS";
const GET_ORDER_DETAILS_FAILURE = "GET_ORDER_DETAILS_FAILURE";

export { GET_ORDER_DETAILS_REQUEST, GET_ORDER_DETAILS_SUCCESS, GET_ORDER_DETAILS_FAILURE }