const GET_TODOS_REQUEST = 'GET_TODOS_REQUEST';
const GET_TODOS_SUCCESS = 'GET_TODOS_SUCCESS';
const GET_TODOS_FAILURE = 'GET_TODOS_FAILURE';

const GET_SINGLE_TODO_REQUEST = 'GET_SINGLE_TODO_REQUEST';
const GET_SINGLE_TODO_SUCCESS = 'GET_SINGLE_TODO_SUCCESS';
const GET_SINGLE_TODO_FAILURE = 'GET_SINGLE_TODO_FAILURE';

const ADD_TODOS_REQUEST = 'ADD_TODOS_REQUEST';
const ADD_TODOS_SUCCESS = 'ADD_TODOS_SUCCESS';
const ADD_TODOS_FAILURE = 'ADD_TODOS_FAILURE';

const DELETE_TODO_REQUEST = 'DELETE_TODO_REQUEST';
const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';
const DELETE_TODO_FAILURE = 'DELETE_TODO_FAILURE';

const TOGGLE_STATUS_REQUEST = 'TOGGLE_STATUS_REQUEST'
const TOGGLE_STATUS_SUCCESS = 'TOGGLE_STATUS_SUCCESS'
const TOGGLE_STATUS_FAILURE = 'TOGGLE_STATUS_FAILURE'

const EDIT_TITLE_REQUEST = 'EDIT_TITLE_REQUEST'
const EDIT_TITLE_SUCCESS = 'EDIT_TITLE_SUCCESS'
const EDIT_TITLE_FAILURE = 'EDIT_TITLE_FAILURE'

export { GET_TODOS_REQUEST, GET_TODOS_SUCCESS, GET_TODOS_FAILURE, 
         GET_SINGLE_TODO_REQUEST, GET_SINGLE_TODO_SUCCESS, GET_SINGLE_TODO_FAILURE, 
         ADD_TODOS_REQUEST, ADD_TODOS_SUCCESS, ADD_TODOS_FAILURE,
         DELETE_TODO_REQUEST, DELETE_TODO_SUCCESS, DELETE_TODO_FAILURE,
         TOGGLE_STATUS_REQUEST, TOGGLE_STATUS_SUCCESS, TOGGLE_STATUS_FAILURE,
         EDIT_TITLE_REQUEST, EDIT_TITLE_SUCCESS, EDIT_TITLE_FAILURE };